---
- hosts: vmlab
  user: student
  become: yes
  vars:
    seneca_id: yourSenecaID
  tasks:
    - name: Update Apache
      yum:
        name: httpd
        state: latest

    - name: Install EPEL
      yum:
        name: epel-release
        state: present

    - name: Remove tree package
      yum:
        name: tree
        state: absent

    - name: Set hostname
      hostname:
        name: "{{ seneca_id }}"

    - name: Create user with sudo access
      user:
        name: "{{ seneca_id }}"
        shell: /bin/bash
        groups: wheel
        append: yes

    - name: Create lab directories
      file:
        path: "/home/{{ seneca_id }}/ops445/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        mode: '0755'
      loop: [1,2,3,4,5,6,7,8]

